apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080   # Host port for browser access
